[module "rbac"]
	name = github.com/starter-go/rbac


[xxx-rbac-dao-set "ram"] 
	enabled = 1
	priority = -100

[xxx-rbac-dao-set "unsupported"] 
	enabled = 1
	priority = -9999

[daoset "rbac"]
	selector = .rbac-dg

[rbac-data-group "memory"]
	enabled = 0
	priority = -1
	class = mem-rbac-dg rbac-dg
